#!/bin/bash
#Not dependent on any running auth2 server
#source venv/bin/activate && python manage.py test authome --keepdb
source .env.standalone
export IGNORE_LOADING_ERROR=True;export CACHE_SERVER CACHE_SERVER_OPTIONS ; uv run python manage.py test authome --keepdb --pattern="test_auth.py"
