# Generated by Django 4.2.16 on 2025-02-27 05:59

import authome.models.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0047_alter_auth2cluster_options_and_more'),
    ]

    operations = [
    ]
