# Generated by Django 4.2.16 on 2025-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0049_trafficcontrol_exempt_groups_and_more'),
    ]

    operations = [
    ]
