# Generated by Django 4.2.16 on 2025-03-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0050_trafficcontrol_block_alter_debuglog_category_and_more'),
    ]

    operations = [
    ]
