# Generated by Django 5.2.8 on 2026-03-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0054_auth2cluster_directconnect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debuglog',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Create cookie'), (11, 'Update cookie'), (12, 'Delete cookie'), (20, 'Upgrade session'), (21, 'Session already upgraded'), (22, 'Upgrade non-exist session'), (30, 'Migrate session'), (31, 'Session already migrated'), (32, 'Migrate non-exist session'), (40, 'Move session'), (41, 'Session already moved'), (42, 'Move non-exist session'), (50, 'Auth2 Cluster Not Available'), (101, 'Auth2 Interconnection Timeout'), (102, 'Authentication Too Slow'), (201, 'LB key not match'), (202, 'Domain not match'), (210, 'Session cookie hacked'), (200, 'Error')], default=10),
        ),
        migrations.RunSQL("DROP TABLE IF EXISTS authome_trafficcontrol_exempt_groups CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS authome_trafficcontrollocation CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS authome_trafficcontrol CASCADE;"),
    ]
