# Generated by Django 5.2.14 on 2026-07-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authome', '0055_remove_trafficcontrollocation_tcontrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='groupid',
            field=models.SlugField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
